import { Mulish } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Mulish({
  subsets: ["latin"],
  subsets: ['cyrillic'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeroUIProvider>
          <Navbar/>
          {children}
          <Footer/>
        </HeroUIProvider>
      </body>
    </html>
  );
}