import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  subsets: ['cyrillic'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <img src="/logo.svg" alt="" />
          <div className="navigation">
            <Link href="/#services">Услуги</Link>
            <Link href="/#licenses">Лицензии</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
